### ISSUE TITLE
Camera Record not working and i didn't get video record thumbnail and video file.

### ISSUE THREAD

**Issue by akhil-0181** [robertlevonyan/camerax-demo#14]
I have run your code image capture working fine but when i record video than it's not working video was not recorded and i didn't get any video thumbnail.

**Comment by robertlevonyan** [comment]
do you get any errors?

**Comment by akhil-0181** [comment]
No

**Comment by robertlevonyan** [comment]
Have you debugged the code, or do you looked the onError function?

**Comment by robertlevonyan** [comment]
I've pushed an update, please check it.
