### ISSUE TITLE
Ensure focused before taking photo

### ISSUE THREAD

**Issue by fzyzcjy** [robertlevonyan/camerax-demo#16]
Hi thanks for this demo! However, when taking photo, it is **not** ensured that scene is focused. Therefore, users have to manually tap or wait to focus, before they can tap the "take photo" button. How can I solve this problem? Because it is quite annoying for users :/

**Comment by robertlevonyan** [comment]
Hi. You can check this `cameraControl.startFocusAndMetering()`

**Comment by fzyzcjy** [comment]
Hi thanks for the reply. However it will trigger a whole focus process which is quite slow, and unnecessary when it is already focused...

**Comment by robertlevonyan** [comment]
it seems there isn't option for tap to focus in CameraX

**Comment by fzyzcjy** [comment]
@robertlevonyan Hi I do not mean "tap to focus". However, I mean ensure focused before taking photo.
