### ISSUE TITLE
This example won't run - you have an old gradle .... ..... .....

### ISSUE THREAD

**Issue by kaizer1** [robertlevonyan/camerax-demo#18]
This example won't run - you have an old gradle .... ..... .....  

Before posting examples, at least check whether they work or not ...

   
<img width="884" alt="Снимок экрана 2021-10-28 173443" src="https://user-images.githubusercontent.com/5073933/139277925-0f94d710-892e-44f8-8e2a-88720aae076b.png">

**Comment by robertlevonyan** [comment]
What exactly is old in gradle?

**Comment by steve47457** [comment]
Thank you, but the `gradle-wrapper.properties` file doesn't exist in your project. It would be much better for everyone if you can simply update this GitHub project :) Appreciate it!

**Comment by robertlevonyan** [comment]
It shouldn't be in any project. It is added automatically when you open the project. So it is there ))

**Comment by steve47457** [comment]
Thanks for the reply but I don't have a gradle-wrapper.properties file anywhere

**Comment by steve47457** [comment]
I do not have this issue with other projects on GitHub, thank you for your time.

**Comment by robertlevonyan** [comment]
after you clone the project, please import it in Android studio instead of opening

**Comment by steve47457** [comment]
@robertlevonyan I still get the same issue, unfortunately
