### ISSUE TITLE
Back camera stretching on custom aspect ratio and wrong output video resolution

### ISSUE THREAD

**Issue by mikhail-kiselev-dev** [robertlevonyan/camerax-demo#20]
I have a samsung galaxy m10 with resolution 720 x 1520 pixels, 19:9 ratio.
Video recorded from camera is 1920 x 908.
When I'm using camerax, including your project - back camera is stretching and output video resolution is 1920 x 1080.
I need to use Camera2 instead, or it possible to fix on camerax?

**Comment by robertlevonyan** [comment]
You can use whatever aspect ratio you want with your camera configuration

`val aspectRatio = aspectRatio(metrics.widthPixels, metrics.heightPixels)`

this is how it is implemented for now, you can change it to smth like this

`val aspectRatio = aspectRatio(1920, 908)`

I believe this should work

**Comment by mikhail-kiselev-dev** [comment]
As `aspectRatio()` returns only 16/9 and 4/3 - preview still stretching and video res still 1920x1080 (note that I want to place my preview on whole screen).
P.S: when I run android/camera-samples Camera2Video project (with list of resolutions on cameras) - I didn't found 1920x908. It is possible that my device just cutting video on hardware level or something?

**Comment by robertlevonyan** [comment]
I think it depends on lib version you are using. In the version used in sample you can set ratio as I wrote in previous comment.

**Comment by mikhail-kiselev-dev** [comment]
If we talk about VideoFragment, `aspectRatio()` fun is:
```
private fun aspectRatio(width: Int, height: Int): Int {
        val previewRatio = max(width, height).toDouble() / min(width, height)
        if (abs(previewRatio - RATIO_4_3_VALUE) <= abs(previewRatio - RATIO_16_9_VALUE)) {
            return AspectRatio.RATIO_4_3
        }
        return AspectRatio.RATIO_16_9
    }
```
So it returns only 16_9 and 4_3. Both ratios impossible to fit in 19:9 without stretching or cutting.
Or I don't understand something?(
Also I tried `.setTargetResolution()` istead of `.setTargetAspectRatio()` - same result.

**Comment by robertlevonyan** [comment]
No you are correct. This are the ratios supported by CameraX. You can try to set resolution, but I think it will not change the ratio.

**Comment by robertlevonyan** [comment]
I'm closing the issue since the issue you mentioned is in fact an API restriction by CameraX
