### ISSUE TITLE
Android 11 Torch is not working 

### ISSUE THREAD

**Issue by rizwankhanMiranshah** [robertlevonyan/camerax-demo#21]
in android 11 flash on torch is not working

**Comment by robertlevonyan** [comment]
Can you test on another device, because on my device it works fine.

**Comment by robertlevonyan** [comment]
@rizwankhanMiranshah did you test it?

**Comment by rizwankhanMiranshah** [comment]
Yes i fix it , its working you need to update some dependencies

**Comment by robertlevonyan** [comment]
Okay. Will update them. Thanks.
