### ISSUE TITLE
Can't launch camera

### ISSUE THREAD

**Issue by volionhiemvh** [robertlevonyan/camerax-demo#29]
I have a problem, with some devices won't start the camera,If I add about 30 more characters to the app id, the app won't work with some devices, If the app id has few characters, the camera works fine, is there any way to fix it

**Comment by robertlevonyan** [comment]
What do you mean by app id?

**Comment by volionhiemvh** [comment]
I use a Nokia X10 android 13, when I set the app id as "com.robertlevonyan.demo.camerax" the app works normally when I change the app id to "com.robertlevonyan.demo.cameraxxxxx" it doesn't work. when removing the characters in the app id it will work. Is there any relationship between camera x and app id length?

**Comment by volionhiemvh** [comment]
https://www.youtube.com/shorts/VZuhwpYafR0

**Comment by robertlevonyan** [comment]
There isn't any connection, btw when you change the application id it is becoming another application

**Comment by robertlevonyan** [comment]
I will suggest you to debug the code
